insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("001","17021790","FÉLIX MOLINA MORALES","MORELOS #9","M.8","951 192 71 09");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("002","83795","ANTONIO MOLINA MORALES","BENITO JUAREZ #1","M. 8","951 4970265");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("003","285436","FEDERICO MOLINA MORALES","BENITO JUAREZ #1","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("004","133087","CRESCENCIANO MOLINA MORALES","BENITO JUAREZ #1","M.8","951 210 71 79");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("005","198503","JUAN BAUTISTA CRUZ","BENITO JUAREZ #20","M.2","951 129 56 60");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("006","133090","ESTANISLAO BAUTISTA NÚÑEZ","BENITO JUAREZ #3","M.8","55 3 21 14");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("007","21571","FORTINO RUIZ MÉNDEZ","BENITO JUAREZ #4","M.2","951 196 50 05");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("008","238016","ANTONIO CRUZ CRUZ","BENITO JUAREZ #6","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("009","458890","JUSTINO CRUZ HERNÁNDEZ","BENITO JUAREZ #5 ","M.2","951 136 79 68");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("010","232365","EUDOSIO LÓPEZ GÓMEZ","BENITO JUAREZ #7","M.8","951 275 70 90");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("011","133688","VILIUIFA MATÍAS GONZALES","BENITO JUAREZ #7","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("012","15060890","GAUDENCIO NÚÑEZ LÓPEZ","BENITO JUAREZ #7","M.3","951 232 41 91");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("013","634850","NICOLÁS LÓPEZ GARCÍA","BENITO JUAREZ #8","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("014","329596","JUAN PÉREZ","BENITO JUAREZ S/N","M.8","951 2178764");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("015","1331","ELVIRA GARCÍA MARTÍNEZ","BENITO JUAREZ #9","M.2","951 2862079");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("016","800845","GERMÁN GARCÍA MARTÍNEZ","BENITO JUAREZ S/N","M.3","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("017","423221","MANUEL NÚÑEZ GARCÍA","BENITO JUAREZ #13","M.4","55 3 20 08");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("018","423238","SEBASTIÁN GARCÍA SANTIAGO","BENITO JUAREZ #15","M.7","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("019","192868","BIVIANA NÚÑEZ LÓPEZ","BENITO JUAREZ #3","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("020","92877","GREGORIO NÚÑEZ LÓPEZ","BENITO JUAREZ #3","M.4","951 346 96 91 ");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("021","13019497","DONACIANO NÚÑEZ LÓPEZ","BENITO JUAREZ #14","M. 4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("022","430523","GUADALUPE NÚÑEZ MARTÍNEZ","","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("023","683160","HÉCTOR NÚÑEZ MELCHOR","","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("024","FIJO","FRANCISCO NÚÑEZ MELCHOR","","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("025","1331","CRISÓFORO GARCÍA LUIS","BENITO JUAREZ #25","M.7","9514978701");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("026","14063732","AGUSTÍN GARCÍA LUIS","","M.7","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("027","15056431","RAFAEL NÚÑEZ MARTÍNEZ","","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("028","2185603","IRMA LUIS MARTÍNEZ","BENITO JUAREZ #16","M.4","951 271 68 94");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("029","11054633","MANUEL NÚÑEZ GARCÍA","BENITO JUAREZ","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("030","844339","CORNELIO MÉNDEZ NÚÑEZ","","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("031","110554633","MANUEL NÚÑEZ GARCÍA","BENITO JUAREZ S/N","M.7","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("032","2249159","PROCESO GÓMEZ GARCÍA","BENITO JUAREZ #10","M.6","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("033","1331","FRANCISCO GARCÍA GARCÍA","BENITO JUAREZ #9","M.5","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("034","423230","MARCIAL GARCÍA GARCÍA","BENITO JUAREZ","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("035","99072464","ISMAEL MÉNDEZ GARCÍA","BENITO JUAREZ #17","M.6","951 269 54 73");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("036","17021797","NICOLÁS MÉNDEZ GARCÍA","BENITO JUAREZ #18","M.6","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("037","428848","JOSÉ GARCÍA MARTÍNEZ","BENITO JUAREZ #20","M.5","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("038","317285","RUFINO CRUZ MORALES","BENITO JUAREZ","M.6","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("039","16087104","CRISPÍN PÉREZ LÓPEZ","BENITO JUAREZ  ESQ. LAS FLORES","M.6","951 3632985");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("040","FIJO","CRISPÍN PÉREZ LÓPEZ","BENITO JUAREZ ESQ. LAS FLORES","M.6","9513632985");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("041","316062","RAFAEL CRUZ BAUTISTA","BENITO JUAREZ #3","M.6","951 290 23 11");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("042","13816","JUAN MORALES LÓPEZ","BENITO JUAREZ LAS FLORES","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("043","332822","AGUSTÍN GÓMEZ NÚÑEZ","NACIONAL #86","S/M","951 165 94 36");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("044","224815","CORNELIO LÓPEZ NÚÑEZ","NACIONAL #87","S/M","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("045","430176","ROBERTO LÓPEZ NÚÑEZ","NACIONAL #86","S/M","951 474 66 62");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("046","98009452","RAFAEL MATEO HERNÁNDEZ","HIDALGO S/N","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("047","2184900","LUCIO MORALES LÓPEZ","HIDALGO #90","","951 233 42 08");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("048","S/N","BERNARDO MORALES LÓPEZ","NACIONAL #90","S/M","55 3 22 76/ 951 127 24 98");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("049","13009734","JUAN MORALES GARCÍA","HIDALGO Y NACIONAL #89","S/M","951 233 42 08");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("050","214975","JUAN MORALES LÓPEZ","NACIONAL #69","S/M","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("051","423211","PABLO GARCÍA MORALES","HIDALGO #1","M.4","951 188 46 89");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("052","185572","CELSO GÓMEZ MÉNDEZ","HIDALGO S/N","M.4","951 185 47 13");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("053","223793","JAIME GÓMEZ MÉNDEZ","HIDALGO S/N","M.4","951 183 47 13");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("054","404380","DIONISIO CRUZ GÓMEZ","HIDALGO S/N","M.5","951 1111967");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("055","1331","EMILIO CRUZ LÓPEZ","HIDALGO #18","M.5","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("056","2030548","RICARDO GÓMEZ GARCÍA","","M.4","951 183 47 13");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("057","99235","LUCIO GARCÍA MARTÍNEZ","HIDALGO #2","M.5","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("058","2249753","FRANCISCO GARCÍA MARTÍNEZ","HIDALGO #3","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("059","1300473","AGUSTÍN GARCÍA CRUZ","HIDALGO #4","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("060 ","13010176","ROGELIO GARCÍA NÚÑEZ","HIDALGO #5","M.5","951 1970883");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("061","343853","CRESCENCIA GARCÍA MARTÍNEZ","HIDALGO #5","M.5","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("062","1331","ABRAHAM GARCÍA MOLINA","HIDALGO #6","M.5","951 125 41 47");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("063","15039419","ANDRÉS GARCÍA MOLINA","HIDALGO #6","M.5","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("064","70494","BENITO GARCÍA NÚÑEZ","HIDALGO #5","M.5","951 125 41 47");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("065","1334","EUSTAQUIO GÓMEZ GARCÍA","HIDALGO #10","M.6","951 320 70 88");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("066","15056499","SALOMÓN GARCÍA NÚÑEZ","HIDALGO #2","M.7","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("067","17033619","ANASTASIO GARCÍA NÚÑEZ","HIDALGO #","M.6","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("068","331104","ESTHER NÚÑEZ LUIS","HIDALGO #12","M.7","951 307 11 02");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("069","133096","CRISTINO CRUZ NÚÑEZ","HIDALGO #13","M.6","55 3 20 76");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("070","226948","RAFAEL CRUZ BAUTISTA","HIDALGO #14","M.6","951 290 23 11");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("071","202045","EUSEBIO CRUZ MORALES","HIDALGO #8","M.6","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("072","940394","FRANCISCO NÚÑEZ NÚÑEZ","HIDALGO #15","M.7","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("073","456537","PABLO GARCÍA GARCÍA","HIDALGO #16","M.6","951 531 01 67");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("074","424827","LAUREANO NÚÑEZ NÚÑEZ","HIDALGO #15","M.7","951 282 61 28");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("075","345514","MANUEL NÚÑEZ NÚÑEZ","HIDALGO#15","M.7","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("076","106335","MARGARITO GARCÍA GARCÍA","HIDALGO #18","M.14","951 458 58 97");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("077","341571","FIDENCIO NÚÑEZ MARTÍNEZ","NIÑO ARTILLERO #27","M.4","951 116 59 89");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("078","1301695","FIDENCIO NÚÑEZ MARTÍNEZ","NIÑO ARTILLERO #27","M.4","951 116 56 89");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("079","915856","MANUEL NÚÑEZ BAUTISTA","NIÑO ARTILLERO #24","M.4","951 195 1222");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("080","430410","ALFREDO NÚÑEZ MARTÍNEZ","NIÑO ARTILLERO #24","M.3","951 256 41 55");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("081","70309","FIDENCIO NÚÑEZ MARTÍNEZ","NIÑO ARTILLERO #27","M.4","951 116 59 89");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("082","13016689","JUAN NÚÑEZ MÉNDEZ","PRIV. NIÑO ARTILLERO ","M.4","951 305 3526");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("083","99072052","MARCIANO NÚÑEZ JERÓNIMO","NIÑO ARTILLERO #24","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("084 ","15065896","PEDRO NÚÑEZ GARCÍA","PRIV. NIÑO ARTILLERO S/N","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("085","13004495","LIDIA CRUZ MARTÍNEZ","NIÑO ARTILLERO#24","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("086","15066483","CARLOS FERNANDO SANTIAGO NÚÑEZ","NIÑO ARTILLERO S/N","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("087","13069892","JESÚS NÚÑEZ GARCÍA","NIÑO ARTILLERO #22","M.4","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("088","198585","APOLINAR NÚÑEZ GARCÍA","NIÑO ARTILLERO #22","M.4","951 199 07 40");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("089","224980","ANGELINA MARTÍNEZ MARTÍNEZ","NIÑO ARTILLERO S/N","M.3","951 399 55 12");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("090","312179","JUAN NÚÑEZ GARCÍA","","M.3","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("091","695159","CARLOS GARCÍA MARTÍNEZ","NIÑO ARTILLERO S/N","M.4","951 570 51 13");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("092","3019367","NICOLÁS NÚÑEZ GARCÍA","NIÑO ARTILLERO","M.7","5532024");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("093","396640","ISAÍAS GARCÍA GARCÍA","NIÑO ARTILLERO #18","M.7","951 190 22 28");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("094","198192","IGNACIO GARCÍA GARCÍA","NIÑO ARTILLERO #18","M.7","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("095","366680","LÁZARO CRUZ SANTIAGO","NIÑO ARTILLERO S/N","M.8","951 415 15 15");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("096","13051330","FÉLIX MOLINA MORALES","NIÑO ARTILLERO S/N ","M.8","55 32359");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("097","227231","RAFAEL MATEO HERNÁNDEZ","NIÑO ARTILLERO #11","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("098","192906","JUAN BAUTISTA CRUZ","MOGOTE","M.20","9511295660");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("099","474497","FAUSTO PÉREZ LÓPEZ","","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("100","14062200","GUALTERIO NÚÑEZ NÚÑEZ","HIDALGO #12","M.7","951 244 48 15");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("101","14062200","NICOLÁS NÚÑEZ JERÓNIMO","NIÑO ARTILLERO #13","M.7","55 3 20 85");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("102","105995","GERARDO BAUTISTA GARCÍA","NIÑO ARTILLERO #12","M.8","951 367 2740");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("103","83156","MIGUEL RAMÍREZ GARCÍA","NIÑO ARTILLERO #10","M.8","55 3 20 00");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("104","291698","ELÍAS RAMÍREZ GARCÍA","NIÑO ARTILLERO #10","M.8","55 3 20 00");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("105","15065282","NICOLÁS NÚÑEZ JERÓNIMO","NIÑO ARTILLERO #13","M.7","55 3 20 85");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("106","146152","PEDRO NÚÑEZ MÉNDEZ","","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("107","430343","FÉLIX MANCERA NÚÑEZ","NIÑO ARTILLERO #10","M.14","5532006");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("108","331669","PLUTARCO MANCERA NÚÑEZ","NIÑO ARTILLERO #10","M.14","951 244 97 45");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("109","226567","MARIO MANCERA NÚÑEZ","NIÑO ARTILLERO #10","M.14","9513664569");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("110","226894","CAMERINO MANCERA NÚÑEZ","NIÑO ARTILLERO #10","M.14","9513664569");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("111","2248824","ANDRÉS GARCÍA MORALES","NIÑO ARTILLERO S/N","M.14","951586 9444");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("112","309270","ESTHER GARCÍA MARTÍNEZ","NIÑO ARTILLERO 7","M.14","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("113","11054636","NORMA SANTIAGO GARCÍA","PRIV. NIÑO ARTILLERO S/N","M.14","951 221 68 74");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("114","70495","ELEUTERIO GARCÍA MARTÍNEZ","NIÑO ARTILLERO #6","M.15","951 177 05 30");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("115","237783","FRANCISCO CRUZ BAUTISTA","NIÑO ARTILLERO S/N","M.15","951 231 45 82");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("116","291935","ESTANISLAO CRUZ BAUTISTA","PRIV. NIÑO ARTILLERO S/N","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("117","434321","INÉS GARCÍA MARTÍNEZ","","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("118","227118","SALVADOR CRUZ BAUTISTA","","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("119","22974","GUSTAVO GARCÍA MÉNDEZ","PRIV. NIÑO ARTILLERO S/N","M.14","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("120","FIJO","MIGUEL RAMÍREZ GARCÍA","PRIV. NIÑO ARTILLERO S/N","M.15","55 3 20 00");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("121","2096523","HIPÓLITO RAMÍREZ HERNÁNDEZ","NIÑO ARTILLERO S/N","M.14","951 472 71 30");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("122","342941","AGUSTÍN GARCÍA LUIS","PRIV. NIÑO ARTILLERO S/N","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("123","238014","LUIS GARCÍA MÉNDEZ","NIÑO ARTILLERO","M.14","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("124","14063733","JUAN GARCÍA NÚÑEZ","COLON#19","M.2","951 242 3130");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("125","422863","BERTIN GARCÍA MARTÍNEZ","COLON","M.2","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("126","83705","PEDRO NÚÑEZ MARTÍNEZ","COLON #16","M.3","951 322 73 79");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("127","223642","WILBER MARTÍNEZ GARCÍA","COLON #15","M.2","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("128","422832","SATURNINO LÓPEZ GARCÍA","COLON #13","M.2","951 252 05 47");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("129","221559","GUSTAVO NÚÑEZ GARCÍA","COLON#14","M.3","951 588 32 51");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("130","341994","ADALBERTO LÓPEZ PÉREZ","COLON S/N","M.2","951 323 50 47");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("131","317977","FLORIBERTO JERÓNIMO LÓPEZ","COLON #9","M.2","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("132","9158814","FÉLIX NÚÑEZ MÉNDEZ","COLON","M.3","9512170119");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("133","183220","ALBERTO NÚÑEZ HERNÁNDEZ","COLON #7","M.2","951 230 4225");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("134","634853","FILIBERTO NÚÑEZ GARCÍA","COLON #8","M.3","951 113 00 82");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("135","453068","ISAAC GARCÍA GARCÍA","COLON #5","M.2","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("136","9803020","JOSÉ NÚÑEZ GARCÍA","COLON #6","M.3","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("137","1821665","PEDRO CRUZ HERNÁNDEZ","COLON#3","M.2","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("138","66509","ANDRÉS NÚÑEZ MOLINA","COLON #2","M.3","951 344 58 22");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("139","485","POLICARPO CRUZ HERNÁNDEZ","COLON #1","M.2","951 399 28 47");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("140","100 24 30","ESTANISLAO BAUTISTA NÚÑEZ","20 DE NOVIEMBRE #24","","55 3 21 14");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("141","77 01 08","PONCIANO NÚÑEZ LÓPEZ","20 DE NOVIEMBRE ","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("142","22 36 24","PROCESO NÚÑEZ MARTÍNEZ","20 DE NOVIEMBRE S/N","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("143","01 30 65","BERNARDO NÚÑEZ LUIS","20 DE NOVIEMBRE","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("144","Fijo","MATIAS MARTÍNEZ LUIS","20 DE NOVIEMBRE","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("145","30 10 52 7","ESTANISLAO BAUTISTA NÚÑEZ","20 DE NOVIEMBRE","","55 3 21 14");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("146","34 21 85","JUSTINO MÉNDEZ MORALES","20 DE NOVIEMBRE #14","M.17","951 231 18 60");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("147","130 194 95","JUAN ALBERTO GÓMEZ LUIS","20 DE NOVIEMBRE #11","M.1","951 295 25 28");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("148","23 76 47","BONIFACIO MÉNDEZ GARCÍA","20 DE NOVIEMBRE","M.1","951 476 07 20");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("149","22 69 20","ALFONSO CRUZ GARCÍA","20 DE NOVIEMBRE","M.1","9512828046");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("150","22 23 48","BONIFACIO MÉNDEZ HIPÓLITO","20 DE NOVIEMBRE ","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("151","47 38 20","BULMARO GARCÍA CRUZ","20 DE NOVIEMBRE #8","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("152","45 31 57","LUCAS GARCÍA CRUZ","20 DE NOVIEMBRE #7","M.17","951 240 58 60");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("153","14 32 146","PATRICIO GARCÍA LÓPEZ","20 DE NOVIEMBRE#6","M.17","954 131 4285");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("154","31 23 49","LÁZARO GARCÍA CRUZ","20 DE NOVIEMBRE","M.18","951 412 55 08");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("155","99 07 24 70","JULIA BAUTISTA CRUZ","20 DE NOVIEMBRE #4","M.17","951 231 89 88");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("156","16 94 76","LEOPOLDO ZARATE SALINAS","20 DE NOVIEMBRE #3","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("157","19 76 30","CAJA SOLIDARIA","20 DE NOVIEMBRE ","M.18","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("158","34 18 94","BERNARDO NÚÑEZ LUIS","20 DE NOVIEMBRE ","M.18","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("159","","MUNICIPIO","20 DE NOVIEMBRE ","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("160","","MERCADO","20 DE NOVIEMBRE ","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("161","68 31","GUSTAVO MARTÍNEZ BAUTISTA","ZARAGOZA#1","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("162","22 49 68 6","MARGARITA LÓPEZ GARCÍA","ZARAGOZA#2","M.10","951 188 46 89");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("163","96 02 75","TEODORO GARCÍA CRUZ","ZARAGOZA","M.17","9513200246");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("164","13 30 68","JUAN GARCÍA NÚÑEZ","ZARAGOZA #8","M.18","951 224 67 66");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("165","83 98 9","MANUEL ZARATE NÚÑEZ","ZARAGOZA #5","M.10","951 111 42 86");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("166","160 23 42 2","JOSÉ LUIS NOLASCO CRUZ","ZARAGOZA#5","M.17","951 1075267");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("167","97 58 54","LUIS NOLASCO LÓPEZ","ZARAGOZA#5","M.17","951 107 5267");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("168","13 30 67","FLAVIO PÉREZ LÓPEZ","ZARAGOZA #11","M.10","951 287 28 48");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("169","42 32 44","MARCELINO GARCÍA MÉNDEZ","ZARAGOZA #13","M.17","951 162 74 69");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("170","34 50 66","FILIBERTO GARCÍA NÚÑEZ","ZARAGOZA  #13","M.18","951 162 74 69");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("171","51 57 83"," JULIO GARCÍA NÚÑEZ","ZARAGOZA #12","M.18","951 162 74 69 ");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("172","16 95 54","JUAN LUIS NÚÑEZ MARTÍNEZ","ZARAGOZA #14","M.10","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("173","Fijo","OSCAR NÚÑEZ NÚÑEZ","ZARAGOZA","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("174","13 31 10 07","JUAN MÉNDEZ LÓPEZ","2° PRIV. ZARAGOZA #17","M.11","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("175","14 7696","ROSA LUIS GARCÍA","2° PRIV. ZARAGOZA","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("176","16 95 54","BENJAMÍN LÓPEZ NÚÑEZ","2° PRIV. ZARAGOZA","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("177","22 23 43","RUPERTO LUIS GARCÍA","2° PRIV. ZARAGOZA #15","10","951 128 05 56");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("178","13 30 94","RUPERTO LUIS GARCÍA","ZARAGOZA #16","11","951 128 05 56");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("179","02 31 29","SERGIO NÚÑEZ NÚÑEZ","ZARAGOZA #18","M.18","951 307 95 51");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("180","00 179 026","ERNESTO MÉNDEZ LÓPEZ","ZARAGOZA #17","M.11","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("181","20 71 94","ROSENDO GARCÍA VÁZQUEZ","ZARAGOZA #19","M.11","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("182","133 055","MARTIN GARCÍA CRUZ","ZARAGOZA #19","M.11","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("183","22 50 22","FLAVIO LUIS MORALES","ZARAGOZA #20","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("184","14 15 59","PAULA MORALES LÓPEZ","ZARAGOZA #23","M.11","951 498 66 39");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("185","130 194 99","EUSEBIO GARCÍA NÚÑEZ","ZARAGOZA#21","M.17","951 544 85 25");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("186","14 82 94","ADELA GARCÍA BAUTISTA","ZARAGOZA #24","M.11","951 111 53 58 ");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("187","40 47 27","MARTHA LUIS MORALES","ZARAGOZA S/N","M.11","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("188","130 105 97","MARCELINO REYES LÓPEZ","ZARAGOZA #21","M.17","951 475 7744");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("189","133","RAFAEL MATEO HERNÁNDEZ","ZARAGOZA","M.18","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("190","140 602 66","GILDARDO GARCÍA MARTÍNEZ","ZARAGOZA","M.11","951 273 06 10");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("191","08 22 24","EMILIO SANTIAGO MÉNDEZ","ZARAGOZA #25","M.17","9512727998");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("192","Fijo","ESTANISLAO BAUTISTA NUÑEZ","DIOS NUNCA MUERE S/N","M.17","55 3 21 14");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("193","45 65 88","CIRO GARCÍA CRUZ","DIOS NUNCA MUERE S/N","M.16","9513549386");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("194","915 11 48","MATILDE GARCÍA CRUZ","DIOS NUNCA MUERE ","M.16","951 504 89 99");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("195","915 41 48","PEDRO MÉNDEZ HIPÓLITO","DIOS NUNCA MUERE ","M.16","951 395 04 05/951 134 38 66");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("196","915 95 96","ISIDRO ARAGÓN MORALES","DIOS NUNCA MUERE#8","M.16","951 157 6445");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("197","915 41 52","DEMETRIO ARAGÓN MORALES","DIOS NUNCA MUERE, FLORES MAGON #8","M.16","951 134 09 61");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("198","16 93 74","MANUEL ARAGÓN LUIS","DIOS NUNCA MUERE","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("199","13 30 70","RODRIGO MARTÍNEZ BAUTISTA","DIOS NUNCA MUERE #7","M.16","951 194 3514");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("200","10 56 40","AARÓN ARAGÓN GÓMEZ","DIOS NUNCA MUERE#6","M.16","5532328");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("201"," 29 24 46","SERGIO MARTÍNEZ GARCÍA","PRIV. ZARAGOZA ","M.16","951 310 67 62");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("202","42 32 42","LEOBARDO ARAGÓN GÓMEZ","PRIV. ZARAGOZA #5","M.16","951 324 04 26");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("203","13 30 61","MODESTO GARCÍA NÚÑEZ","DIOS NUNCA MUERE #2","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("204","76 01 37","JUAN LUIS MORALES","DIOS NUNCA MUERE","M.11","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("205","839437","SALVADOR LÓPEZ CRUZ","MOGOTE","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("206","332512","HERMELO MARTÍNEZ GARCÍA","MOGOTE","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("207","915854","LAURO MÉNDEZ LÓPEZ","MOGOTE","M.15","951 591 6902");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("208","139095","GUILLERMO CRUZ PÉREZ","MOGOTE #24","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("209","635445","ISRAEL MARTÍNEZ MÉNDEZ","MOGOTE 204","M.16","951 360 2170");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("210","39433","FELIPE HIPÓLITO MÉNDEZ","MOGOTE #205","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("211","3118","AUSENCIO HERNÁNDEZ GARCÍA","MOGOTE #5","M.16","248 181 3252");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("212","338226","MAURO HERNÁNDEZ LÓPEZ","MOGOTE #5","M.12","951 342 5710");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("213","423225","DESIDERIA MELCHOR GÓMEZ","MOGOTE ","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("214","634855","SALVADOR RAMÍREZ REYES","MOGOTE #224","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("215","114197","FÉLIX GARCÍA LÓPEZ","MOGOTE S/N","M.16","951 230 42 25");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("216","5201327","ROGELIO GARCÍA GARCÍA","MOGOTE S/N","M.16","951 230 42 25");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("217","35348","EUSEBIO GARCÍA GARCÍA","MOGOTE","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("218","133105","ABELINO MELCHOR JERÓNIMO","MOGOTE #223","M.16","951 311 27 50");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("219","15039416","VIRGINIA MELCHOR JERÓNIMO","MOGOTE #223","M.16","951 311 27 50");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("220","2249316","LIBORIA MARTÍNEZ BAUTISTA","MOGOTE #19","M.15","951 199 88 85");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("221","9907555","BRAULIO NÚÑEZ HERNÁNDEZ","MOGOTE S/N","M.15","951 344 58 22");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("222","1331331","IGNACIO GARCÍA ARAGÓN","MOGOTE #32","M.20","951 458 32 47");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("223","42889","ANSELMO GARCÍA MARTÍNEZ","MOGOTE ","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("224","432027","MIGUEL ÁNGEL CRUZ SANTIAGO","MOGOTE ","","9511145559");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("225","Fijo","MIGUEL ÁNGEL CRUZ SANTIAGO","MOGOTE ","","9511145559");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("226","888592","EMILIO LÓPEZ GARCÍA","AGUSTIN MELGAR #211","M.16","951 231 64 24");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("227","423250","MANUEL LÓPEZ GARCÍA","AGUSTIN MELGAR ","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("228","Fijo","BIVIANA NÚÑEZ LÓPEZ","AGUSTIN MELGAR ","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("229","421191","ROBERTO CRUZ LÓPEZ","AGUSTIN MELGAR ","M.22","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("230","292088","FRANCISCO HERNÁNDEZ LÓPEZ","AGUSTIN MELGAR ","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("231","9907555","FRANCISCO CRUZ GARCÍA","AGUSTIN MELGAR #31","M.20","951 283 99 59");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("232","312107","ANTONIO MÉNDEZ MELCHOR","AGUSTIN MELGAR #29","M.20","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("233","133108","JUSTINO CRUZ HERNÁNDEZ","AGUSTIN MELGAR S/N","M.22","951 250 53 80");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("234","","GABRIEL ZARATE NÚÑEZ","AGUSTIN MELGAR ","M.22","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("235","","JUSTINO CRUZ HERNÁNDEZ","AGUSTIN MELGAR ","M.22","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("236","14063737","CARLOS GÓMEZ GARCÍA","GUERRERO #6","M.20","951 344 94 63");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("237","16003209","ABEL GÓMEZ GARCÍA","GUERRERO","M.22","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("238","234130","FRANCISCO GARCÍA GARCÍA","GUERRERO #27","M.20","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("239","92244486","ADRIAN GARCÍA GARCÍA","GUERRERO S/N","M.20","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("240","Fijo","NICOLÁS CRUZ GARCIA","GUERRERO S/N","M.20","951 441 7668 ");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("241","769736","REY GARCÍA LÓPEZ","GUERRERO S/N","M.20","9512551050");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("242","224373","PRIMITIVO NÚÑEZ ANTONIO","GUERRERO","M.20","951 456 36 74");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("243","327951","PEDRO  GARCÍA RAMÍREZ","GUERRERO","M.20","951 183 10 44");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("244","8011897","SALOMÓN BAUTISTA NÚÑEZ","AGUSTIN MELGAR S/N","M.20","951 2330008");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("245","435610","LUCIO GARCÍA GARCÍA","AGUSTIN MELGAR ","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("246","0","DANIEL MÉNDEZ MOLINA","AGUSTIN MELGAR S/N","M.16","951 258 68 10");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("247","990724467","ADELFO MÉNDEZ MOLINA","AGUSTIN MELGAR ","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("248","13001473","ERNESTO MÉNDEZ LÓPEZ","AGUSTIN MELGAR S/N","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("249","Fijo","FLORENCIA HERNÁNDEZ HERNÁNDEZ","AGUSTIN MELGAR ","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("250","423241","CRISPÍN MARTÍNEZ MÉNDEZ","AGUSTIN MELGAR ","M.16","951 310 67 62");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("251","24400","JACINTO CRUZ GARCÍA","AGUSTIN MELGAR #229","M.16","9511160352");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("252","292273","FÉLIX CRUZ GARCÍA","AGUSTIN MELGAR #229","M.16","9511160352");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("253","635145","EVARISTO CRUZ PÉREZ","AGUSTIN MELGAR S/N","M.16","951 412 59 42");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("254","105897","MATEO GARCÍA LOPEZ","","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("255","1925066","ANTONIO CRUZ GARCÍA","PIPILA","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("256","683168","HERMELINDA GOMES MÉNDEZ","PIPILA #222","M.16","971 117 02 56");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("257","2249313","YOLANDA GARCÍA CRUZ","PIPILA #226","M.17","951 164 45 80");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("258","331140","MARGARITO GARCÍA GARCÍA","CHAPULTEPEC #16","M.16","951 395 47 98");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("259","456687","PEDRO MÉNDEZ HIPÓLITO","CHAPULTEPEC S/N","M.16","951 395 04 05/951 134 38 66");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("260","2006589","HONORIO GARCÍA GARCÍA","CHAPULTEPEC #10","M.16","951 164 29 89");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("261","Fijo","PEDRO GARCÍA GARCÍA","CHAPULTEPEC","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("262","94039441","ENRIQUE MARTÍNEZ GARCÍA","CHAPULTEPEC","M.16","951 118 20 14");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("263","9159276","GENARO GARCÍA CRUZ","CHAPULTEPEC","M.17","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("264","770387","PERFECTO MÉNDEZ GÓMEZ","CHAPULTEPEC","M.17","951 112 66 35");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("265","1303687","SANTIAGO ARAGÓN MORALES","CHAPULTEPEC S/N","M.16","951 473 70 29");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("266","94079442","ANDRÉS CRUZ MARTÍNEZ","PRIV. CHAPULTEPEC S/N","M.17","951 282 54 53");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("267","683179","ELVIRA MARTÍNEZ GARCÍA","PRIV. CHAPULTEPEC ","M.16","953 102 31 44");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("268","14053963","LUCIO ARAGÓN MORALES","PRIV. CHAPULTEPEC","M.16","951 260 50 00");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("269","15039414","ÁNGEL NÚÑEZ SANTIAGO","PRIV. CHAPULTEPEC","M.16","951 118 48 14");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("270","227577","AGUSTÍN GARCÍA MELCHOR","PRIV. CHAPULTEPEC #22","M.16","951 519 39 43");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("271","758","BARTOLOMÉ CRUZ HIPÓLITO","CHAPULTEPEC #23","M.17","951 269 50 08");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("272","19 72 64","JERÓNIMO MARTÍNEZ LÓPEZ","DIOS NUNCA MUERE #2","M.18","951 439 67 65");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("273","76 01 37","CIPRIANO HERNÁNDEZ GARCÍA","DIOS NUNCA MUERE ","M.15","951 3956701");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("274","13 30 63","SILVINO HERNÁNDEZ GARCÍA","DIOS NUNCA MUERE ","M.15","951 195 01 15");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("275","39 44","LAUREANO LÓPEZ PÉREZ","DIOS NUNCA MUERE #199","M.15","951 544 84 61");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("276","140 637 34","REY HERNÁNDEZ CRUZ","DIOS NUNCA MUERE #138","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("277","Fijo","PABLO HERNÁNDEZ CRUZ","DIOS NUNCA MUERE ","M.16","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("278","63 48 49","UBALDO HERNÁNDEZ LÓPEZ","DOLORES ","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("279","221 605","EMILIO HERNÁNDEZ LUIS","DOLORES ","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("280","42 90 90","UBALDO HERNÁNDEZ LÓPEZ","DOLORES ","M.15","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("281","447 71 22","DAVID GARCÍA BAUTISTA","DOLORES ","M.18","951 278 21 82");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("282","68 31 53","SIXTO BAUTISTA LÓPEZ","DOLORES #251","M.15","951 305 89 31");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("283","65 58 9","INOCENCIO BAUTISTA LÓPEZ","PRIV. DOLORES #214","M.16","951 223 53 57");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("284","182 15 45","POLICARPO BAUTISTA GARCÍA","PRIV. DOLORES #213","M.15","951 439 96 28");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("285","45 33 47","VÍCTOR BAUTISTA GARCÍA","DOLORES ","M.16","+118186443080");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("286","29 08 70","PASCASIO MARTÍNEZ LÓPEZ","DOLORES","M.19","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("287","22 74 32","ISABEL BAUTISTA GARCÍA","DOLORES S/N","M.16","951 209 64 77");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("288","222358","BERTHA MOLINA MARTÍNEZ","LIBERTAD #194","M.19","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("289","4310720","FÉLIX GÓMEZ MARTÍNEZ","LIBERTAD #180","M.20","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("290","13046704","PASCASIO MARTÍNEZ LÓPEZ","LIBERTAD ","M.19","951 240 15 53");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("291","15039412","EUSEBIO GARCÍA GÓMEZ","LIBERTAD #39","19","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("292","439434","NICOLÁS NÚÑEZ JERÓNIMO","LIBERTAD #187","M.19","9512096000");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("293","473756","REYNALDO GARCÍA BAUTISTA","LIBERTAD ","M.18","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("294","6074430","GUADALUPE CRUZ CRUZ","LIBERTAD ","M.18","951 179 0256");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("295","1405230","MATEO LÓPEZ LÓPEZ","LIBERTAD #186","M.20","951 190 46 98");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("296","291840","CRISPÍN LÓPEZ LÓPEZ","LIBERTAD ","M.19","951 1000815");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("297","13125249","BERNABÉ MÉNDEZ CRUZ","LIBERTAD","M.18","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("298","2185300","VICTORIANO LÓPEZ PÉREZ","LIBERTAD#184","M.19","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("299","22044","HERIBERTO LÓPEZ MORALES","VICENTE SUAREZ #1","M.19","951 313 14 72");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("300","1331","HONORIO LÓPEZ PÉREZ","VICENTE SUAREZ ","M.19","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("301","44077","GUILLERMINA LÓPEZ MELCHOR","VICENTE SUAREZ","M.20","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("302","106311","MARCO LÓPEZ GARCÍA","VICENTE ZUAREZ","MZ.19","951 439 58 40");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("303","263818","ANTONIO LÓPEZ MORALES","VICENTE SUAREZ S/N","M.19","951 439 58 40");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("304","683180","ANASTASIO LÓPEZ MORALES","VICENTE SUAREZ #179","M.19","951 187 70 34");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("305","635319","ALFREDO LUIS MANCERA","DIOS NUNCA MUERE","m12","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("306","971005","TEODORO LÓPEZ MELCHOR","DIOS NUNCA MUERE #11","M.19","951 284 64 29");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("307","908586","TOMASA GARCÍA MARTÍNEZ","DIOS NUNCA MUERE #14","M.12","951 282 45 65");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("308","423154","SANTIAGO GARCÍA BAUTISTA","DIOS NUNCA MUERE ","M.12","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("309","14053968","FÉLIX GARCÍA HERNÁNDEZ","LIBERTAD #45","M.12","951 243 82 51");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("310","215054","ROMÁN GARCÍA HERNÁNDEZ","LIBERTAD ","M.12","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("311","683151","GREGORIO LUIS NÚÑEZ","LIBERTAD #43","M.12","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("312","515781","DONACIANO HERNÁNDEZ GARCÍA","LIBERTAD #44","M.18","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("313","99072054","SILVINO HERNÁNDEZ GARCÍA","LIBERTAD #42","M.19","951 184 94 70");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("314","2006606","TOBÍAS REYES GARCÍA","LIBERTAD ","M.12","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("315","13155805","TOBÍAS REYES GARCÍA","LIBERTAD  #42","M.12","951 330 40 85");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("316","14063740","ZEFERINO MARTÍNEZ GARCÍA","LIBERTAD S/N","M.19","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("317","226740","CIPRIANO REYES MARTÍNEZ","LIBERTAD #40","M.12","951 311 49 84");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("318","16066475","ADELFO MARTÍNEZ MARTÍNEZ","LIBERTAD S/N","M.19","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("319","13008237","ADALBERTO LÓPEZ GÓMEZ","LIBERTDA #39","M.12","951 303 5487");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("320","151728","MAURO LÓPEZ GARCÍA","LIBERTAD","M.12","951 367 57 76");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("321","405243","NICOLÁS LÓPEZ GARCÍA","LIBERTAD#38","M.12","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("322","474470","CIRILO MARTÍNEZ MÉNDEZ","LIBERTAD #36","M.12","55 3 21 94");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("323","423208","ALBERTO MARTÍNEZ GARCÍA","LIBERTDA #37","M.11","951 109 39 12 ");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("324","423208","JUVENAL MARTÍNEZ MÉNDEZ","LIBERTAD #36","M.12","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("325","183200","FILEMÓN MARTÍNEZ GARCÍA","LIBERTAD ","M.11","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("326","169747","BENJAMÍN LÓPEZ NÚÑEZ","LIBERTAD ","M.12 ","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("327","423235","FRANCISCO LÓPEZ NÚÑEZ","LIBERTAD #34","M.12","951 358 02 26");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("328","133106","JUAN GARCÍA PÉREZ","PRIV. ZARAGOZA #16","M.10","951 112 24 66");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("329","312602","LADISLAO MARTÍNEZ GARCÍA","PRIV. LIBERTAD #3","","951 476 97 11");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("330","234988","BENJAMÍN LÓPEZ NÚÑEZ","PRIV. LIBERTAD  ","M.12","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("331","222827","BERTÍN CRUZ HERNÁNDEZ","PRIIV. LIBERTAD","","951 268 78 20");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("332","222342","FILEMÓN MARTÍNEZ GARCÍA","PRIV. LIBERTAD ","M.11","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("333","13062846","JOSÉ REYES LÓPEZ","PRIV. LIBERTAD S/N","M.12","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("334","17018554","FÉLIX REYES LÓPEZ","PRIV. LIBERTAD S/N","M.12","951 237 83 25");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("335","345213","NORBERTO GARCÍA SANTIAGO","LIBERTAD","M.13","951 340 49 75");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("336","423206","MANUEL GARCÍA MANCERA","LIBERTAD #33","M.10","9512275073");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("337","3042901","SANTIAGO GARCÍA MANCERA","LIBERTAD ","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("338","183332","REYNALDO HERNÁNDEZ LÓPEZ","LIBERTAD","M.13,14","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("339","133062","SOFÍA CRUZ MARTÍNEZ","LIBERTAD #27","M.10","951 104 87 74");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("340","3281721","ANATALIA PÉREZ LUIS","LIBERTAD #29","M.13","951 544 10 01");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("341","378470","PEDRO MARTÍNEZ HERNÁNDEZ","PRIV. LIBERTAD #28","M.13","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("342","2023379","SOFÍA CRUZ MARTÍNEZ","LIBERTAD #27","M.13","951 104 87 74");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("343","908586","TOMASA GÓMEZ MARTÍNEZ","LIBERTAD","M.10","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("344","331688","MARINO GARCÍA CRUZ","LIBERTAD #29","M.10","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("345","423169","JOSÉ GÓMEZ MARTÍNEZ","LIBERTAD","M.10","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("346","181360","DAVID GARCÍA BARRIGA","LIBERTAD #25","M.10","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("347","95573","ISAÍAS CRUZ BAUTISTA","LIBERTAD S/N","M.10","951 358 87 75");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("348","14053970","LUCIO GARCÍA GARCÍA","LIBERTAD#23","M.13","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("349","342899","PEDRO GARCÍA LUIS","LIBERTAD S/N","M.9","951 303 96 47");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("350","15030420","AGUSTÍN LÓPEZ MARTÍNEZ","1° PRIV. ZARAGOZA","M.10","951 107 20 14");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("351","971242","MARIO GARCÍA MOLINA","1° PRIV. ZARAGOZA","M.9","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("352","147699","AGUSTÍN LÓPEZ MARTÍNEZ","1° PRIV. ZARAGOZA","M.10","951 107 20 14");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("353","122864","IGNACIO MÉNDEZ MELCHOR","1° PRIV. ZARAGOZA","M9","951 415 48 59");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("354","99072465","CLAUDIO LÓPEZ GÓMEZ","1° PRIV. ZARAGOZA","M.9","951 208 09 46");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("355","343519","EUSEBIO HIPÓLITO GARCÍA","LIBERTAD #23","M.13","951 170 54 16");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("356","13008232","PAULA MARTÍNEZ MÉNDEZ","LIBERTAD #22","M.9","951 415 48 59");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("357","6344847","MERCEDES NÚÑEZ JERÓNIMO","LIBERTAD #24","","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("358","70490","IGNACIO GARCÍA MOLINA","LIBERTAD","M.9","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("359","980146","ANASTASIO LUIS ANTONIO","LIBERTAD #20","M.13","951 239 85 75");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("360","192869","FLORENCIANO LUIS PÉREZ","LIBERTAD #19 ","M. 13","951 392 17 59");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("361","15039486","FRANCISCO LUIS PÉREZ","LIBERTAD #19","M.13","951 235 11 96");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("362","13077391","ROQUE MARTÍNEZ LÓPEZ","LIBERTAD #18","M.14","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("363","683159","MARÍA GARCÍA MORALES","LIBERTAD ","M.9","951 509 2509");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("364","421199","JULIÁN LÓPEZ GARCÍA","LIBERTAD","M.14","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("365","423224","ERNESTO LÓPEZ MÉNDEZ","LIBERTAD","M.9","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("366","1302777","ROQUE MARTÍNEZ LÓPEZ","LIBERTAD #15","M.9","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("367","423412","LIDIA MARTÍNEZ GARCÍA","LIBERTAD","M.13","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("368","4232320","FRANCISCO CRUZ GARCÍA","LIBERTAD #13","M.9","951 457 48 96");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("369","99072468","MARIO GARCÍA PÉREZ","LIBERTAD","M.9","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("370","341896","JUANA NÚÑEZ LÓPEZ","MORELOS","M.14","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("371","17021788","JOSÉ GARCÍA JERÓNIMO","LIBERTAD #11","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("372","17028725","VICTORIANO GARCÍA JERÓNIMO","LIBERTAD #11","M.8","951 129 16 62");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("373","215026","LUCIO GARCÍA JERÓNIMO","LIBERTAD #11","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("374","423240","CAYETANO GARCÍA LÓPEZ","LIBERTAD #10","M.13 ","55 3 20 09");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("375","15039418","LUCAS MORALES LÓPEZ","LIBERTAD S/N","M.13","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("376","133097","GUSTAVO MARTÍNEZ BAUTISTA","LIBERTAD #9","M.8","9512905511");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("377","222350","LUCIO MORALES LÓPEZ","LIBERTAD#7","M.13","5532212");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("378","1821890","MAXIMO GARCÍA GARCÍA","LIBERTAD #5","M.13","55 3 23 41");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("379","681362","JUSTO BAUTISTA LÓPEZ","LIBERTAD","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("380","98009411","JORGE GARCÍA GARCÍA","LIBERTAD","M.13","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("381","950880","RUFINO BAUTISTA GARCÍA","LIBERTAD #4","M.8","951 274 18 34");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("382","133080","JULIO GARCÍA GARCÍA","LIBERTAD #3","M.13","951 260 49 89 ");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("383","13051328","AMADO BAUTISTA GARCÍA","LIBERTAD #1","M.8","951 183 73 04");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("384","456400","VICTORINO GARCÍA GARCÍA","LIBERTAD #2","M.13","951 188 03 19");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("385","99239864","FREDDY LÓPEZ GARCÍA","MORELOS#16","M.9","951 338 34 64 ");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("386","422815","VALERIO LÓPEZ GARCÍA","MORELOS #16","M.9","951 198 58 77");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("387","424830","PEDRO MORALES GARCÍA","MORELOS","M.9","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("388","423234","CARLOS MELCHOR GARCÍA","MORELOS","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("389","222349","FRANCISCO JERÓNIMO NUÑEZ","MORELOS#13","M.9","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("390","133093","LUCIO MORALES GARCÍA","MORELOS #7","M.8","951 233 42 08");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("391","138645","AUSENCIO LUIS GARCÍA","MORELOS","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("392","419384","ALFONSO LUIS GARCÍA","MORELOS #12","M.8","951 311 14 63");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("393","1","CASA DEL REPRESENTANTE","MORELOS","M.8","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("394","105743","ADOLFO LUIS MORALES","MORELOS #11","M.8","951 243 22 50");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("395","328397","ROLANDO MORALES GARCÍA","MORELOS #11","M.9","951 224 49 69");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("396","223784","COMUNAL","MORELOS","M.9","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("397","3770052","EJIDAL","MORELOS","M.9","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("398","222341","GASPAR BAUTISTA LÓPEZ","MORELOS #9","M.2","951 179 80 17");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("399","17018292","FAUSTO NÚÑEZ GARCÍA","MORELOS","M2","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("400","7","IGNACIO GARCÍA MARTÍNEZ","MORELOS #7","M.2","951 257 26 33");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("401","133066","AGUSTÍN JERÓNIMO HERNÁNDEZ","MORELOS","M.1","951 125 19 56");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("402","133072","ÁLVARO NOLASCO LÓPEZ","PRIV. MORELOS #8","M.2","951 226 25 53");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("403","421198","ENRIQUE MARTÍNEZ GARCÍA","PRIV. MORELOS S/N","M.1","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("404","133110","AGUSTÍN JERÓNIMO HERNÁNDEZ","PRIV. MORELOS","M.2","951 125 19 56");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("405","94039447","ÁLVARO NOLASCO LÓPEZ","PRIV. MORELOS #8","M.1","951 226 25 53");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("406","683172","MIGUEL CRUZ GARCÍA","PRIV. MORELSO #7","M.2","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("407","133089","EMILIO SANTIAGO MÉNDEZ","PRIV. MORELOS","M.1","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("408","6831781","TERESA MARTÍNEZ MORALES","PRIV. MORELOS #3","M.2","951 356 93 84");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("409","2006608","NEMESIO GARCÍA SANTIAGO","PRIV. MORELOS#4","M.2","951 217 0148");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("410","11028358","PEDRO GARCÍA LÓPEZ","PRIV. MORELOS#2","M.2","951 128 00 98");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("411","14058967","GELASIO GARCÍA LÓPEZ","PRIV. MORELOS #1","M.2","951 402 06 37");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("412","16087102","NICOLÁS NÚÑEZ GARCÍA","HIDALGO","M.7","");
insert into consumidores(numUsuario, numMedidor, nombreCompleto,  direccion, manzana, telefono) values("413","","CLAUDIO LUIS GARCIA","","","");
