/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import ConexionCloseBD.ConexionBD;
import DAO.DAOException;
import DAO.consumidoresDAO;
import DAO.consumidoresDAOImpl;
import DAO.consumoDAOImpl;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.consumidores;
import modelo.consumo;

/**
 *
 * @author Evelyn
 */
public class Pago extends javax.swing.JFrame {

    double totalAPagar = 0;
    double totalConsumo = 0;
    int aniox;
    int periodox;

    String numUsuarioConsulta;
    Connection conn = null;
    ConexionBD conecionBD = new ConexionBD();

    public Pago(String usuario, int periodo, int anio) {
        initComponents();
//        this.setExtendedState(MAXIMIZED_BOTH);
        aniox = anio;

        periodox = periodo;

        numUsuarioConsulta = usuario;

        llenarPago(usuario, periodo, anio);

    }

    private Pago() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numUsuario = new javax.swing.JTextField();
        otrosPAgos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePeriodo = new javax.swing.JTable();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelManzana = new javax.swing.JLabel();
        jLabelNmedidor = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        pago = new javax.swing.JPanel();
        totalPago = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCobrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelConsumo = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        btnComprobante = new javax.swing.JButton();
        otrosPAgos1 = new javax.swing.JPanel();
        jTextCuota = new javax.swing.JTextField();
        jTextRecargo = new javax.swing.JTextField();
        jTextCooperacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextBonificaciones = new javax.swing.JTextField();
        jTextSanciones = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaMotivo = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jTextVarios = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        contenedor.setBackground(new java.awt.Color(255, 255, 255));

        btnSalir.setBackground(new java.awt.Color(7, 82, 132));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setLabel("SALIR");
        btnSalir.setName("btnSalir"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BUSCAR USUARIO:");

        numUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numUsuario.setForeground(new java.awt.Color(0, 51, 204));
        numUsuario.setEnabled(false);
        numUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numUsuarioKeyReleased(evt);
            }
        });

        otrosPAgos.setBackground(new java.awt.Color(255, 255, 255));
        otrosPAgos.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACIÓN DEL CONSUMIDOR"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("N° Medidor:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Dirección:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Manzana:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Periodos");

        jTablePeriodo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTablePeriodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePeriodo);

        jLabelTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTelefono.setText("###");

        jLabelDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDireccion.setText("###");

        jLabelManzana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelManzana.setText("###");

        jLabelNmedidor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNmedidor.setText("###");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setText("###");

        javax.swing.GroupLayout otrosPAgosLayout = new javax.swing.GroupLayout(otrosPAgos);
        otrosPAgos.setLayout(otrosPAgosLayout);
        otrosPAgosLayout.setHorizontalGroup(
            otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otrosPAgosLayout.createSequentialGroup()
                .addGroup(otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otrosPAgosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(otrosPAgosLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(otrosPAgosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(otrosPAgosLayout.createSequentialGroup()
                                .addGroup(otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(28, 28, 28)
                                .addGroup(otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(otrosPAgosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNmedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 111, Short.MAX_VALUE))
                    .addGroup(otrosPAgosLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        otrosPAgosLayout.setVerticalGroup(
            otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otrosPAgosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNmedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otrosPAgosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pago.setBackground(new java.awt.Color(255, 255, 255));

        totalPago.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalPago.setForeground(new java.awt.Color(255, 51, 51));
        totalPago.setText("#####");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Total a pagar: ");

        btnCobrar.setBackground(new java.awt.Color(7, 82, 132));
        btnCobrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCobrar.setText("COBRAR");
        btnCobrar.setFocusPainted(false);
        btnCobrar.setFocusable(false);
        btnCobrar.setName("btnSalir"); // NOI18N
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Consumo en mts:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Importe consumo:");

        jLabelConsumo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelConsumo.setForeground(new java.awt.Color(0, 0, 204));
        jLabelConsumo.setText("consumo");

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTotal.setText("total");

        btnComprobante.setBackground(new java.awt.Color(7, 82, 132));
        btnComprobante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComprobante.setForeground(new java.awt.Color(255, 255, 255));
        btnComprobante.setText("COMPROBANTE");
        btnComprobante.setFocusPainted(false);
        btnComprobante.setFocusable(false);
        btnComprobante.setName("btnSalir"); // NOI18N
        btnComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pagoLayout = new javax.swing.GroupLayout(pago);
        pago.setLayout(pagoLayout);
        pagoLayout.setHorizontalGroup(
            pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagoLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(35, 35, 35)
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pagoLayout.setVerticalGroup(
            pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagoLayout.createSequentialGroup()
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConsumo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelTotal))))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        otrosPAgos1.setBackground(new java.awt.Color(255, 255, 255));
        otrosPAgos1.setBorder(javax.swing.BorderFactory.createTitledBorder("OTROS PAGOS"));

        jTextCuota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextCuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCuotaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCuotaKeyReleased(evt);
            }
        });

        jTextRecargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextRecargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextRecargoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextRecargoKeyReleased(evt);
            }
        });

        jTextCooperacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextCooperacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCooperacionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCooperacionKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Cuota fija:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Recargos:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Sanciones:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Cooperación:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Bonificaciones:");

        jTextBonificaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextBonificaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextBonificacionesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextBonificacionesKeyReleased(evt);
            }
        });

        jTextSanciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextSanciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSancionesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextSancionesKeyReleased(evt);
            }
        });

        jTextAreaMotivo.setColumns(20);
        jTextAreaMotivo.setRows(5);
        jScrollPane4.setViewportView(jTextAreaMotivo);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Varios:");

        jTextVarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextVarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextVariosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextVariosKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("Nota: en caso de sancion poner motivo");

        javax.swing.GroupLayout otrosPAgos1Layout = new javax.swing.GroupLayout(otrosPAgos1);
        otrosPAgos1.setLayout(otrosPAgos1Layout);
        otrosPAgos1Layout.setHorizontalGroup(
            otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otrosPAgos1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14)
                    .addGroup(otrosPAgos1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(99, 99, 99)
                        .addGroup(otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCooperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextBonificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextVarios, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        otrosPAgos1Layout.setVerticalGroup(
            otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otrosPAgos1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCooperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBonificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otrosPAgos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextVarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(otrosPAgos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(otrosPAgos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(otrosPAgos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(otrosPAgos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        otrosPAgos.getAccessibleContext().setAccessibleName(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String fechaformateada = formato.format(new Date());
            int numConsumidorTemp = Integer.parseInt(numUsuarioConsulta);
            conn = conecionBD.conexion();
            consumoDAOImpl daoConsumo = new consumoDAOImpl(conn);
            consumo c = new consumo();

            consumo consumo = daoConsumo.buscarConsumo(numConsumidorTemp, periodox, aniox);

            c.setPeriodo(consumo.getPeriodo());
            c.setAnio(aniox);
            c.setNumUsuario(String.valueOf(numUsuarioConsulta));
            c.setLecturaActual(consumo.getLecturaActual());
            c.setConsumoMedidor(consumo.getConsumoMedidor());
            c.setPrecio(consumo.getPrecio());
            c.setImporteConsumo(consumo.getImporteConsumo());
            c.setCoutaFija(Double.valueOf(jTextCuota.getText()));
            c.setRecargos(Double.valueOf(jTextRecargo.getText()));
            c.setCooperacion(Double.valueOf(jTextCooperacion.getText()));
            c.setBonificaciones(Double.valueOf(jTextBonificaciones.getText()));
            c.setSanciones(Double.valueOf(jTextSanciones.getText()));
            c.setVarios(Double.valueOf(jTextVarios.getText()));
            c.setTotalPagar(Double.valueOf(totalPago.getText()));
            c.setFechaPAgo(fechaformateada);
            c.setNotas(jTextAreaMotivo.getText());
            c.setAviso(consumo.getAviso());
            c.setStatus(1);
            //System.err.println("datos a antes de atualizar "+ consumo.toString());
            //System.err.println("datos a guardar"+ c.toString());
            daoConsumo.actualizar(c);
            bloquearCajas();
            btnComprobante.show(true);
            btnCobrar.enable(false);
            btnCobrar.show(false);
            
        } catch (DAOException ex) {
            Logger.getLogger(Pago.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (conn != null) {
                conecionBD.cerrarConexion();
            }
        }

    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        Principal prin = new Principal();
        prin.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void numUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numUsuarioKeyReleased

    }//GEN-LAST:event_numUsuarioKeyReleased

    private void jTextCuotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCuotaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextCuotaKeyPressed

    private void jTextRecargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRecargoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextRecargoKeyPressed

    private void jTextCooperacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCooperacionKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextCooperacionKeyPressed

    private void jTextBonificacionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBonificacionesKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextBonificacionesKeyPressed

    private void jTextSancionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSancionesKeyPressed

    }//GEN-LAST:event_jTextSancionesKeyPressed

    private void jTextVariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextVariosKeyPressed

    }//GEN-LAST:event_jTextVariosKeyPressed

    private void numUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numUsuarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numUsuarioKeyPressed

    private void jTextCuotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCuotaKeyReleased
        // TODO add your handling code here:
        calcularMonto();
    }//GEN-LAST:event_jTextCuotaKeyReleased

    private void jTextRecargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRecargoKeyReleased
        calcularMonto();
    }//GEN-LAST:event_jTextRecargoKeyReleased

    private void jTextCooperacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCooperacionKeyReleased
        calcularMonto();
    }//GEN-LAST:event_jTextCooperacionKeyReleased

    private void jTextBonificacionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBonificacionesKeyReleased
        calcularMonto();
    }//GEN-LAST:event_jTextBonificacionesKeyReleased

    private void jTextSancionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSancionesKeyReleased
        calcularMonto();
    }//GEN-LAST:event_jTextSancionesKeyReleased

    private void jTextVariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextVariosKeyReleased
        calcularMonto();
    }//GEN-LAST:event_jTextVariosKeyReleased

    private void btnComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprobanteActionPerformed

    public void llenarPago(String usuario, int periodo, int anio) {
        //System.out.println(numUsuario.getText().length());
        //if (numUsuario.getText().length() == 3) {
        try {

            numUsuario.setText(usuario);
            int numConsumidorTemp = Integer.parseInt(usuario);
//                int periodo = 10;
//                int anio = 2019;
            conn = conecionBD.conexion();
            consumidoresDAO dao = new consumidoresDAOImpl(conn);
            consumoDAOImpl daoConsumo = new consumoDAOImpl(conn);
            consumidores consumidor = dao.buscarConsumidor(numConsumidorTemp);
            jLabelNmedidor.setText(String.valueOf(consumidor.getNumMedidor()));
            jLabelNombre.setText(String.valueOf(consumidor.getNombreCompleto()));
            jLabelDireccion.setText(String.valueOf(consumidor.getDireccion()));
            jLabelManzana.setText(String.valueOf(consumidor.getManzana()));
            jLabelTelefono.setText(String.valueOf(consumidor.getTelefono()));

            //consumo consumo = daoConsumo.buscarConsumo(numConsumidor, periodo, anio);
            consumo consumo = daoConsumo.buscarConsumo(numConsumidorTemp, periodo, anio);

            jTextCuota.setText(String.valueOf((consumo.getCoutaFija())));
            jTextRecargo.setText(String.valueOf(consumo.getRecargos()));
            jTextCooperacion.setText(String.valueOf(consumo.getCooperacion()));
            jTextBonificaciones.setText(String.valueOf(consumo.getBonificaciones()));
            jTextSanciones.setText(String.valueOf(consumo.getSanciones()));
            jTextVarios.setText(String.valueOf(consumo.getVarios()));
            jTextAreaMotivo.setText(consumo.getAviso());

            totalConsumo = consumo.getTotalPagar();
            jLabelTotal.setText(String.valueOf(totalConsumo));

            if (consumo.getStatus() == 1) {
                btnComprobante.enable(true);
                btnComprobante.show(true);
                btnCobrar.enable(false);
                btnCobrar.show(false);
                jLabel13.setText("PAGADO: " + consumo.getFechaPAgo());
                bloquearCajas();
            } else {
                btnComprobante.show(false);
            }
            calcularMonto();
        } catch (DAOException ex) {
            Logger.getLogger(Pago.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (conn != null) {
                conecionBD.cerrarConexion();
            }
        }
//        } else {
//            System.out.println("cadena menor a 3");
//        }
    }

    public void calcularMonto() {
        double couata = 0;
        double recargos = 0;
        double cooperacion = 0;
        double bonifi = 0;
        double sancion = 0;
        double varios = 0;
        try {
            couata = Double.valueOf(jTextCuota.getText());
            recargos = Double.valueOf(jTextRecargo.getText());
            cooperacion = Double.valueOf(jTextCooperacion.getText());
            bonifi = Double.valueOf(jTextBonificaciones.getText());
            sancion = Double.valueOf(jTextSanciones.getText());
            varios = Double.valueOf(jTextVarios.getText());
            totalAPagar = totalConsumo + couata + recargos + cooperacion + bonifi + sancion + varios;
            totalPago.setText(String.valueOf(totalAPagar));
        } catch (Exception e) {

            System.out.println("vista.Pago.calcularMonto()" + e);
        }

    }

    public void bloquearCajas() {
        jTextCuota.enable(false);
        jTextRecargo.enable(false);
        jTextCooperacion.enable(false);
        jTextBonificaciones.enable(false);
        jTextSanciones.enable(false);
        jTextVarios.enable(false);
        jTextAreaMotivo.enable(false);
        ;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pago().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnComprobante;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConsumo;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelManzana;
    private javax.swing.JLabel jLabelNmedidor;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablePeriodo;
    private javax.swing.JTextArea jTextAreaMotivo;
    private javax.swing.JTextField jTextBonificaciones;
    private javax.swing.JTextField jTextCooperacion;
    private javax.swing.JTextField jTextCuota;
    private javax.swing.JTextField jTextRecargo;
    private javax.swing.JTextField jTextSanciones;
    private javax.swing.JTextField jTextVarios;
    private javax.swing.JTextField numUsuario;
    private javax.swing.JPanel otrosPAgos;
    private javax.swing.JPanel otrosPAgos1;
    private javax.swing.JPanel pago;
    private javax.swing.JLabel totalPago;
    // End of variables declaration//GEN-END:variables
}
