/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import ConexionCloseBD.ConexionBD;
import DAO.DAOException;
import DAO.consumidoresDAO;
import DAO.consumidoresDAOImpl;
import DAO.consumoDAOImpl;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.consumidores;
import modelo.consumo;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Evelyn
 */
public class reporte extends javax.swing.JFrame {

    Connection conn = null;
    ConexionBD conecionBD = new ConexionBD();
    String fechaformateada;
    
    public reporte() {
        initComponents();
//        this.setExtendedState(MAXIMIZED_BOTH);
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        fechaformateada = formato.format(new Date());
        String anio =  fechaformateada.substring(0, 4);
        int mes = Integer.parseInt(fechaformateada.substring(5, 7));
        anioConsulta.setText(anio);
        
        if(mes == 12 || mes == 1){
            jcPerido.setSelectedIndex(0);
            informacion.setText("INFORMACIÓN DEL PERIODO DICIEMBRE-ENERO");
        }else if(mes == 2 || mes == 3){
            jcPerido.setSelectedIndex(1);
            informacion.setText("INFORMACIÓN DEL PERIODO FEBRERO-MARZO");
        }else if(mes == 4 || mes == 5){
            informacion.setText("INFORMACIÓN DEL PERIODO ABRIL-MAYO");
            jcPerido.setSelectedIndex(2);
        }else if(mes == 6 || mes == 7){
            informacion.setText("INFORMACIÓN DEL PERIODO JUNIO-JULIO");
            jcPerido.setSelectedIndex(3);
        }else if(mes == 8 || mes == 9){
            informacion.setText("INFORMACIÓN DEL PERIODO AGOSTO-SEPTIEMBRE");
            jcPerido.setSelectedIndex(4);          
        }else if(mes == 10 || mes == 11){
            informacion.setText("INFORMACIÓN DEL PERIODO OCTUBRE-NOVIEMBRE");
            jcPerido.setSelectedIndex(5);           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir1 = new javax.swing.JButton();
        pago = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabelPersonas = new javax.swing.JLabel();
        jLabelDinero = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelPersonasadeudan = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelPersonaspagado = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLsanciones = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jrecargos = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLtotalAgua = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLcoperacion = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLBonificacion = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLVarios = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcPerido = new javax.swing.JComboBox<String>();
        btnAdeudo = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnPagos1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        anioConsulta = new javax.swing.JTextField();
        btnReporte = new javax.swing.JButton();
        btnPagos2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsumos = new javax.swing.JTable();
        informacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1182, 744));

        btnSalir1.setBackground(new java.awt.Color(7, 82, 132));
        btnSalir1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("REGRESAR AL MENÚ");
        btnSalir1.setName("btnSalir"); // NOI18N
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        pago.setBackground(new java.awt.Color(255, 255, 255));
        pago.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Total de personas: ");

        jLabelPersonas.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelPersonas.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPersonas.setText("###");

        jLabelDinero.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelDinero.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDinero.setText("###");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel17.setText("Total dinero:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("N° personas adeudan: ");

        jLabelPersonasadeudan.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelPersonasadeudan.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPersonasadeudan.setText("###");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("N° personas pagaron: ");

        jLabelPersonaspagado.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelPersonaspagado.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPersonaspagado.setText("###");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Total de sanción : ");

        jLsanciones.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLsanciones.setForeground(new java.awt.Color(0, 0, 153));
        jLsanciones.setText("###");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Total de recargos: ");

        jrecargos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jrecargos.setForeground(new java.awt.Color(0, 0, 153));
        jrecargos.setText("###");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Total cosumo de agua: ");

        jLtotalAgua.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLtotalAgua.setForeground(new java.awt.Color(0, 0, 153));
        jLtotalAgua.setText("###");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Total de cooperacion : ");

        jLcoperacion.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLcoperacion.setForeground(new java.awt.Color(0, 0, 153));
        jLcoperacion.setText("###");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Total de bonificacion : ");

        jLBonificacion.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLBonificacion.setForeground(new java.awt.Color(0, 0, 153));
        jLBonificacion.setText("###");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Total de varios : ");

        jLVarios.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLVarios.setForeground(new java.awt.Color(0, 0, 153));
        jLVarios.setText("###");

        javax.swing.GroupLayout pagoLayout = new javax.swing.GroupLayout(pago);
        pago.setLayout(pagoLayout);
        pagoLayout.setHorizontalGroup(
            pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(pagoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))))
                        .addGap(28, 28, 28)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPersonaspagado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPersonasadeudan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLtotalAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel22)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)))
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrecargos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcoperacion, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLBonificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLsanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLVarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pagoLayout.setVerticalGroup(
            pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPersonas)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pagoLayout.createSequentialGroup()
                                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pagoLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelDinero)
                                            .addComponent(jLabel17)))
                                    .addGroup(pagoLayout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLVarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1))
                            .addGroup(pagoLayout.createSequentialGroup()
                                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pagoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabelPersonaspagado))
                                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pagoLayout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLtotalAgua)))
                                            .addGroup(pagoLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabelPersonasadeudan)
                                                    .addComponent(jLabel15)))))
                                    .addGroup(pagoLayout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jLsanciones)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jrecargos, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLcoperacion))
                        .addGap(20, 20, 20)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLBonificacion))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(9, 43, 96));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(9, 43, 96));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("SELECCIONE EL PERIODO A CONSULTAR");

        jcPerido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DICIEMBRE-ENERO", "FEBRERO-MARZO", "ABRIL-MAYO", "JUNIO-JULIO", "AGOSTO-SEPTIEMBRE", "OCTUBRE-NOVIEMBRE" }));

        btnAdeudo.setBackground(new java.awt.Color(7, 82, 132));
        btnAdeudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdeudo.setForeground(new java.awt.Color(255, 255, 255));
        btnAdeudo.setText("ADEUDOS");
        btnAdeudo.setActionCommand("");
        btnAdeudo.setName("btnSalir"); // NOI18N
        btnAdeudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdeudoActionPerformed(evt);
            }
        });

        btnPagos.setBackground(new java.awt.Color(7, 82, 132));
        btnPagos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPagos.setForeground(new java.awt.Color(255, 255, 255));
        btnPagos.setText("PAGOS DEL DÍA");
        btnPagos.setActionCommand("");
        btnPagos.setName("btnSalir"); // NOI18N
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });

        btnPagos1.setBackground(new java.awt.Color(7, 82, 132));
        btnPagos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPagos1.setForeground(new java.awt.Color(255, 255, 255));
        btnPagos1.setText("CONSUMO DE AGUA P/PER");
        btnPagos1.setActionCommand("");
        btnPagos1.setName("btnSalir"); // NOI18N
        btnPagos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagos1ActionPerformed(evt);
            }
        });

        jLabel1.setText("INGRESE EL AÑO A CONSULTAR");

        anioConsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnReporte.setBackground(new java.awt.Color(7, 82, 132));
        btnReporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setText("GENERAR REPORTE");
        btnReporte.setName("btnSalir"); // NOI18N
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnPagos2.setBackground(new java.awt.Color(7, 82, 132));
        btnPagos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPagos2.setForeground(new java.awt.Color(255, 255, 255));
        btnPagos2.setText("PAGOS POR PERIODO");
        btnPagos2.setActionCommand("");
        btnPagos2.setName("btnSalir"); // NOI18N
        btnPagos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdeudo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnPagos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcPerido, javax.swing.GroupLayout.Alignment.LEADING, 0, 232, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(anioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPagos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jcPerido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnPagos2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdeudo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPagos1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTableConsumos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTableConsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableConsumos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        informacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(informacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        this.dispose();
        Principal prin = new Principal();
        prin.setVisible(true);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnAdeudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdeudoActionPerformed
        int mostrar = 0;
        int anioQuery = 0;
        int periodoqury = 0;
        try {
            anioQuery = Integer.parseInt(anioConsulta.getText());
            periodoqury = jcPerido.getSelectedIndex() + 1;

            mostrar = 1;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Favor de ingresar el año a consultar");
        }
        if (mostrar == 1) {
            conn = conecionBD.conexion();
//            consumidoresDAO dao = new consumidoresDAOImpl(conn);
            consumoDAOImpl daoConsumo = new consumoDAOImpl(conn);
            String query = "select * from consumo where anio=" + anioQuery + " and periodo=" + periodoqury + " and status=0;";
            String queryPagado = "select * from consumo where anio=" + anioQuery + " and periodo=" + periodoqury + "  and status=1;";

            List<consumo> consumo;
            List<consumo> consumoPagado;
            int totalPersonasSinPagar = 0;

            try {
                consumo = daoConsumo.busquedaGenerico(query);
                consumoPagado = daoConsumo.busquedaGenerico(queryPagado);

                int toalRegistro = consumo.size();
                int i = 0;

                String matriz[][] = new String[toalRegistro][5];
                String status = "";

                for (consumo c : consumo) {

                    totalPersonasSinPagar = totalPersonasSinPagar + 1;

                    if (c.getStatus() == 1) {
                        status = "PAGADO";
                    } else {
                        status = "PENDIENTE";

                    }

                    String per = String.valueOf(c.getPeriodo());
                    switch (per) {
                        case "1":
                            per = "DICIEMBRE - ENERO";
                            break;
                        case "2":
                            per = "FEBRERO - MARZO";
                            break;
                        case "3":
                            per = "ABRIL - MAYO";
                            break;
                        case "4":
                            per = "JUNIO - JULIO";
                            break;
                        case "5":
                            per = "AGOSTO - SEPTIEMBRE";
                            break;
                        case "6":
                            per = "OCTUBRE - NOVIEMBRE";
                            break;
                    }
                    matriz[i][0] = String.valueOf(i + 1);
                    matriz[i][1] = c.getNumUsuario();
                    matriz[i][2] = (per);

                    matriz[i][3] = status;
                    matriz[i][4] = (String.valueOf(c.getAnio()));

                    i++;
                    System.out.println(i);
                }

                jTableConsumos.setModel(new javax.swing.table.DefaultTableModel(
                        matriz,
                        new String[]{
                            ".", "NUM. USUARIO", "PERIODO", "ESTADO", "AÑO"
                        }
                ));
                jLabelPersonasadeudan.setText(String.valueOf(totalPersonasSinPagar));
                jLabel15.show(true);
                jLabelPersonasadeudan.show(true);
                obtenerDetallar(consumoPagado);
                pintarColumnaTabla();
            } catch (DAOException ex) {
                Logger.getLogger(reporte.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnAdeudoActionPerformed
    void pintarColumnaTabla() {

        jTableConsumos.setDefaultRenderer(Object.class, new PintarCelda());

    }

    void obtenerDetallar(List<consumo> consumoPagado) {
        int totalPersonas = 0;

        int totalPersonasPagado = 0;
        double totalDinero = 0;
        double importeConsumo = 0;
        double coutaFija = 0;
        double recargos = 0;
        double cooperacion = 0;
        double bonificaciones = 0;
        double sanciones = 0;
        double varios = 0;

        for (consumo cp : consumoPagado) {
            totalDinero = totalDinero + cp.getTotalPagar();
            //  importeConsumo=importeConsumo+cp.getTotalPagar();
            coutaFija = coutaFija + cp.getCoutaFija();
            recargos = recargos + cp.getRecargos();
            cooperacion = cooperacion + cp.getCooperacion();
            bonificaciones = bonificaciones + cp.getBonificaciones();
            sanciones = sanciones + cp.getSanciones();
            varios = varios + cp.getSanciones();
            importeConsumo = importeConsumo + cp.getImporteConsumo();
            totalPersonasPagado = totalPersonasPagado + 1;
        }

        totalPersonas = Integer.valueOf(jLabelPersonasadeudan.getText()) + totalPersonasPagado;
        jLabelPersonas.setText(String.valueOf(totalPersonas));

        jLabelPersonaspagado.setText(String.valueOf(totalPersonasPagado));
        jLabelDinero.setText(String.valueOf(totalDinero));

        jLsanciones.setText(String.valueOf(sanciones));
        jrecargos.setText(String.valueOf(recargos));
        jLtotalAgua.setText(String.valueOf(importeConsumo));
//        jLcuotafija.setText(String.valueOf(coutaFija));
        jLcoperacion.setText(String.valueOf(cooperacion));
        jLBonificacion.setText(String.valueOf(bonificaciones));
        jLVarios.setText(String.valueOf(varios));
        //jlmultas.setText(String.valueOf());
    }
    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        conn = conecionBD.conexion();
        consumidoresDAO dao = new consumidoresDAOImpl(conn);
        consumoDAOImpl daoConsumo = new consumoDAOImpl(conn);
        String query = " select * from consumo where status=1  and fechaPAgo ='" + fechaformateada + "';";
        informacion.setText("INFORMACIÓN DE DÍA: " + fechaformateada);

        List<consumo> consumo;
        try {
            consumo = daoConsumo.busquedaGenerico(query);
            int toalRegistro = consumo.size();
            int i = 0;
            String matriz[][] = new String[toalRegistro][6];
            String status = "";

            for (consumo c : consumo) {
                // System.out.println(c.toString());
                if (c.getStatus() == 1) {
                    status = "PAGADO";
                } else {
                    status = "PENDIENTE";

                }

                String per = String.valueOf(c.getPeriodo());
                switch (per) {
                    case "1":
                        per = "DICIEMBRE - ENERO";
                        break;
                    case "2":
                        per = "FEBRERO - MARZO";
                        break;
                    case "3":
                        per = "ABRIL - MAYO";
                        break;
                    case "4":
                        per = "JUNIO - JULIO";
                        break;
                    case "5":
                        per = "AGOSTO - SEPTIEMBRE";
                        break;
                    case "6":
                        per = "OCTUBRE - NOVIEMBRE";
                        break;
                }
                matriz[i][0] = String.valueOf(i + 1);
                matriz[i][1] = c.getNumUsuario();
                matriz[i][2] = (per);
                matriz[i][3] = (String.valueOf(c.getAnio()));
                matriz[i][4] = status;
                matriz[i][5] = "$" + String.valueOf(c.getTotalPagar());
                i++;
            }

            jTableConsumos.setModel(new javax.swing.table.DefaultTableModel(
                    matriz,
                    new String[]{
                        ".", "NUM. USUARIO", "PERIODO", "AÑO", "ESTADO", "Total Pagado"
                    }
            ));

            jLabelPersonasadeudan.setText(String.valueOf(0));
            jLabel15.show(false);
            jLabelPersonasadeudan.show(false);
            obtenerDetallar(consumo);
            pintarColumnaTabla();
        } catch (DAOException ex) {
            Logger.getLogger(reporte.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.err.println("tamaño:  " + consumo.size());


    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
//         conn = conecionBD.conexion();
////         consumidoresDAO dao = new consumidoresDAOImpl(conn);
//         
//         JasperReport reporte = null;
//         String path = "src\\reportes\\comprobante.jasper";
//         
//        try {
//            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
//            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conn);
////            crear vista d ereporte
//            JasperViewer view = new JasperViewer(jprint, false);
//            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//            view.setVisible(true);
//            
//        } catch (JRException ex) {
//            Logger.getLogger(reporte.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnPagos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagos1ActionPerformed
        

        conn = conecionBD.conexion();
        consumoDAOImpl daoConsumo = new consumoDAOImpl(conn);
        String query = "select periodo, anio,sum(consumoMedidor) as total from consumo GROUP BY periodo, anio order by anio desc,periodo asc;";
       
        List<String> consumoAgua;
        consumoAgua = daoConsumo.obtenerTotalConsumoAgua(query);
        String matriz[][] = new String[consumoAgua.size()][6];
            String status = "";
            int j=1;
        for(int i=0; i<=consumoAgua.size()-1;i=i+3, j++){
       
             String per = String.valueOf(consumoAgua.get(i));
                switch (per) {
                    case "1":
                        per = "DICIEMBRE - ENERO";
                        break;
                    case "2":
                        per = "FEBRERO - MARZO";
                        break;
                    case "3":
                        per = "ABRIL - MAYO";
                        break;
                    case "4":
                        per = "JUNIO - JULIO";
                        break;
                    case "5":
                        per = "AGOSTO - SEPTIEMBRE";
                        break;
                    case "6":
                        per = "OCTUBRE - NOVIEMBRE";
                        break;
                }
                matriz[i][0] = String.valueOf(j);
                matriz[i][1] = (per);
                matriz[i][2] = consumoAgua.get(i+1);
                matriz[i][3] = consumoAgua.get(i+2)+ " mts";
                jTableConsumos.setModel(new javax.swing.table.DefaultTableModel(
                    matriz,
                    new String[]{
                        ".","PERIODO", "AÑO", "TOTAL EN METROS"
                    }
            ));

            jLabelPersonasadeudan.setText(String.valueOf(0));
            jLabel15.show(false);
            jLabelPersonasadeudan.show(false);
           
            pintarColumnaTabla();
        
        }
         jLabelPersonas.setText(" ");

        jLabelPersonaspagado.setText(" ");
        jLabelDinero.setText(" ");

        jLsanciones.setText(" ");
        jrecargos.setText(" ");
        jLtotalAgua.setText(" ");
//        jLcuotafija.setText(" ");
        jLcoperacion.setText(" ");
        jLBonificacion.setText(" ");
        jLVarios.setText(" ");
       
    }//GEN-LAST:event_btnPagos1ActionPerformed

    private void btnPagos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagos2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioConsulta;
    private javax.swing.JButton btnAdeudo;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnPagos1;
    private javax.swing.JButton btnPagos2;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel informacion;
    private javax.swing.JLabel jLBonificacion;
    private javax.swing.JLabel jLVarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabelDinero;
    private javax.swing.JLabel jLabelPersonas;
    private javax.swing.JLabel jLabelPersonasadeudan;
    private javax.swing.JLabel jLabelPersonaspagado;
    private javax.swing.JLabel jLcoperacion;
    private javax.swing.JLabel jLsanciones;
    private javax.swing.JLabel jLtotalAgua;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsumos;
    private javax.swing.JComboBox<String> jcPerido;
    private javax.swing.JLabel jrecargos;
    private javax.swing.JPanel pago;
    // End of variables declaration//GEN-END:variables
}
