/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import ConexionCloseBD.ConexionBD;
import DAO.DAOException;
import DAO.consumidoresDAO;
import DAO.consumidoresDAOImpl;
import DAO.consumoDAOImpl;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.consumo;

/**
 *
 * @author Evelyn
 */
public class reporte extends javax.swing.JFrame {

    
    Connection conn = null;
    ConexionBD conecionBD = new ConexionBD();
    public reporte() {
        initComponents();
//        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsumos = new javax.swing.JTable();
        btnSalir1 = new javax.swing.JButton();
        btnAdeudo = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        pago = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        jLabelPersonas = new javax.swing.JLabel();
        jLabelDinero = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelPersonas1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelPersonas2 = new javax.swing.JLabel();
        btnPagos1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1182, 744));

        jTableConsumos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTableConsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableConsumos);

        btnSalir1.setBackground(new java.awt.Color(7, 82, 132));
        btnSalir1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("REGRESAR AL MENÚ");
        btnSalir1.setName("btnSalir"); // NOI18N
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        btnAdeudo.setBackground(new java.awt.Color(7, 82, 132));
        btnAdeudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdeudo.setForeground(new java.awt.Color(255, 255, 255));
        btnAdeudo.setText("ADEUDOS");
        btnAdeudo.setActionCommand("");
        btnAdeudo.setName("btnSalir"); // NOI18N
        btnAdeudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdeudoActionPerformed(evt);
            }
        });

        btnPagos.setBackground(new java.awt.Color(7, 82, 132));
        btnPagos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPagos.setForeground(new java.awt.Color(255, 255, 255));
        btnPagos.setText("PAGOS DEL DÍA");
        btnPagos.setActionCommand("");
        btnPagos.setName("btnSalir"); // NOI18N
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });

        pago.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Total de personas: ");

        btnReporte.setBackground(new java.awt.Color(7, 82, 132));
        btnReporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setText("GENERAR REPORTE");
        btnReporte.setEnabled(false);
        btnReporte.setName("btnSalir"); // NOI18N
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        jLabelPersonas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPersonas.setText("###");

        jLabelDinero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDinero.setText("###");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Total dinero:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("N° personas adeudan: ");

        jLabelPersonas1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPersonas1.setText("###");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("N° personas pagaron: ");

        jLabelPersonas2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPersonas2.setText("###");

        javax.swing.GroupLayout pagoLayout = new javax.swing.GroupLayout(pago);
        pago.setLayout(pagoLayout);
        pagoLayout.setHorizontalGroup(
            pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pagoLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelDinero))
                            .addGroup(pagoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPersonas1))
                            .addGroup(pagoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPersonas2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelPersonas)
                        .addGap(959, 959, 959))))
        );
        pagoLayout.setVerticalGroup(
            pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelPersonas))
                .addGap(13, 13, 13)
                .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pagoLayout.createSequentialGroup()
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabelPersonas1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabelPersonas2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pagoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addComponent(jLabelDinero))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnPagos1.setBackground(new java.awt.Color(7, 82, 132));
        btnPagos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPagos1.setForeground(new java.awt.Color(255, 255, 255));
        btnPagos1.setText("CONSUMO DE AGUA");
        btnPagos1.setActionCommand("");
        btnPagos1.setName("btnSalir"); // NOI18N
        btnPagos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagos1ActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(9, 43, 96));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(9, 43, 96));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnAdeudo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnPagos1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdeudo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagos1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        this.dispose();
        Principal prin = new Principal();
        prin.setVisible(true);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnAdeudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdeudoActionPerformed
          conn = conecionBD.conexion();
                consumidoresDAO dao = new consumidoresDAOImpl(conn);
                consumoDAOImpl daoConsumo = new consumoDAOImpl(conn);
                String query="select * from consumo where status=0;";
                List<consumo> consumo;
        try {
            consumo = daoConsumo.busquedaGenerico(query);
             int toalRegistro = consumo.size();
                    int i = 0;
                    String matriz[][] = new String[toalRegistro][5];
                    String status = "";

                    for (consumo c : consumo) {
                        // System.out.println(c.toString());
                        if (c.getStatus() == 1) {
                            status = "PAGADO";
                        } else {
                            status = "PENDIENTE";

                        }
                        
                        String per = String.valueOf(c.getPeriodo());
                        switch(per){
                            case "1":
                                per = "DICIEMBRE - ENERO";
                                break;
                            case "2":
                                per = "FEBRERO - MARZO";
                                break;
                            case "3":
                                per = "ABRIL - MAYO";
                                break;
                            case "4":
                                per = "JUNIO - JULIO";
                                break;
                            case "5":
                                per = "AGOSTO - SEPTIEMBRE";
                                break;
                            case "6":
                                per = "OCTUBRE - NOVIEMBRE";
                                break;
                        }
                        matriz[i][0] = String.valueOf(i+1);
                        matriz[i][1] = c.getNumUsuario();
                         matriz[i][2] = (per); 
                        
                        matriz[i][3] = status;           
                        matriz[i][4] = (String.valueOf(c.getAnio()));                        
                                            
                        i++;
                        System.out.println(i);
                    }

                    jTableConsumos.setModel(new javax.swing.table.DefaultTableModel(
                            matriz,
                            new String[]{
                               ".", "NUM. USUARIO", "PERIODO", "ESTADO", "AÑO"
                            }
                    ));
                    
                    pintarColumnaTabla();
        } catch (DAOException ex) {
            Logger.getLogger(reporte.class.getName()).log(Level.SEVERE, null, ex);
        }
                    //System.err.println("tamaño:  " + consumo.size());
                   

    }//GEN-LAST:event_btnAdeudoActionPerformed
 void pintarColumnaTabla(){
       
         jTableConsumos.setDefaultRenderer(Object.class, new PintarCelda());
    }
    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
         SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String fechaformateada = formato.format(new Date());
            
            conn = conecionBD.conexion();
                consumidoresDAO dao = new consumidoresDAOImpl(conn);
                consumoDAOImpl daoConsumo = new consumoDAOImpl(conn);
                String query=" select * from consumo where status=1  and fechaPAgo ='"+fechaformateada+"';";
                System.err.println("consulta de hoy"+query);
                List<consumo> consumo;
        try {
            consumo = daoConsumo.busquedaGenerico(query);
             int toalRegistro = consumo.size();
                    int i = 0;
                    String matriz[][] = new String[toalRegistro][6];
                    String status = "";

                    for (consumo c : consumo) {
                        // System.out.println(c.toString());
                        if (c.getStatus() == 1) {
                            status = "PAGADO";
                        } else {
                            status = "PENDIENTE";

                        }
                        
                        String per = String.valueOf(c.getPeriodo());
                        switch(per){
                            case "1":
                                per = "DICIEMBRE - ENERO";
                                break;
                            case "2":
                                per = "FEBRERO - MARZO";
                                break;
                            case "3":
                                per = "ABRIL - MAYO";
                                break;
                            case "4":
                                per = "JUNIO - JULIO";
                                break;
                            case "5":
                                per = "AGOSTO - SEPTIEMBRE";
                                break;
                            case "6":
                                per = "OCTUBRE - NOVIEMBRE";
                                break;
                        }
                        matriz[i][0] = String.valueOf(i+1);
                        matriz[i][1] = c.getNumUsuario();
                        matriz[i][2] = (per);
                        matriz[i][3] = (String.valueOf(c.getAnio()));                        
                        matriz[i][4] = status;                         
                        matriz[i][5] ="$"+ String.valueOf(c.getTotalPagar());
                        i++;                        
                    }

                    jTableConsumos.setModel(new javax.swing.table.DefaultTableModel(
                            matriz,
                            new String[]{
                               ".", "NUM. USUARIO", "PERIODO", "AÑO", "ESTADO", "Total Pagado"
                            }
                    ));
                    
                    pintarColumnaTabla();
        } catch (DAOException ex) {
            Logger.getLogger(reporte.class.getName()).log(Level.SEVERE, null, ex);
        }
                    //System.err.println("tamaño:  " + consumo.size());
                   

    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnPagos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdeudo;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnPagos1;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabelDinero;
    private javax.swing.JLabel jLabelPersonas;
    private javax.swing.JLabel jLabelPersonas1;
    private javax.swing.JLabel jLabelPersonas2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsumos;
    private javax.swing.JPanel pago;
    // End of variables declaration//GEN-END:variables
}
